/*
 * mock-server.mjs — a fake pi session for exercising CONDUCTORS without running pi.
 *
 * Tricks the Accordion app into thinking it's attached to a live pi session: speaks
 * the real wire protocol (v5), streams a real recorded session block-by-block as if a
 * model were generating it, and answers a conductor's out-of-band `completeRequest`
 * with junk. The app's conductor runs for real against the evolving store — the only
 * thing fake is the agent on the far end.
 *
 * What it deliberately does NOT do: apply the `plan` the app sends back. Folding lives
 * in the app's store (substitution, not removal), so a conductor's decisions are
 * visible in the app regardless. The real agent would apply the plan to ITS context;
 * here we just log it. When you connect real pi, the junk completions become real
 * model responses and the logged plans get applied — nothing else changes.
 *
 * Drive model:
 *   • blocks come from app/static/sample-session.jsonl, parsed by the app's own
 *     engine/parse.ts (the proven loader for this file), then re-id'd into the
 *     wire-durable prefix form linearize() emits (u:/a:/r:) so the conductor's fold
 *     guards accept them.
 *   • pacing is TOKENS PER SECOND: a generated block (thinking/text/tool_call) takes
 *     tokens/TPS seconds to "type" before it commits; tool_result and user blocks
 *     commit instantly (a tool result isn't generated by the model).
 *   • the session LOOPS forever. By default each loop appends with fresh ids and
 *     offset turns/order, so context GROWS without bound — sustained budget pressure,
 *     which is what actually exercises a conductor. Set GROW=0 to reset each loop.
 *
 * Connect: `npm run dev` in app/, open http://localhost:1420, type the port (4317)
 * into the manual Connect box, pick your conductor in the sidebar.
 *
 * Env knobs:
 *   PORT=4317     loopback WS port (matches the app's DEFAULT_PORT / manual box)
 *   TPS=60        generation speed in tokens/sec (higher = faster; 1e9 ≈ instant)
 *   CW=60000      context window → budget the app snaps to (smaller = more pressure)
 *   GROW=1        1 = context grows across loops; 0 = reset the store each loop
 *   STEP=0        1 = wait for Enter before each block (overrides TPS pacing)
 *   SAMPLE=<path> override the session file
 *
 * Run: node mock-server.mjs            (or: node mock-server.mjs --selftest)
 */
import { WebSocketServer } from "ws";
import { createJiti } from "jiti";
import * as fs from "node:fs";
import * as path from "node:path";
import * as readline from "node:readline";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const jiti = createJiti(import.meta.url);

// Load the app's REAL modules so the wire can never silently desync from a protocol
// bump (the rot that killed the old mock: it hard-coded protocolVersion 1).
const { parse } = await jiti.import("../app/src/lib/engine/parse.ts");
const { PROTOCOL_VERSION, DEFAULT_PORT } = await jiti.import("../app/src/lib/live/protocol.ts");
const { isDurableId } = await jiti.import("../app/src/lib/live/mapping.ts");

// ── config ───────────────────────────────────────────────────────────────────
const PORT = Number(process.env.PORT || DEFAULT_PORT);
const TPS = Math.max(1, Number(process.env.TPS || 60));
const CW = Number(process.env.CW || 60_000);
const GROW = process.env.GROW !== "0";
const STEP = process.env.STEP === "1";
const SAMPLE = process.env.SAMPLE || path.join(__dirname, "../app/static/sample-session.jsonl");
const JUNK = "[stub completion] fake pi — connect a real pi session for a real model response.";

const est = (s) => Math.ceil((s || "").length / 4) + 4;
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
const GENERATED = new Set(["thinking", "text", "tool_call"]); // typed by the model; the rest commit instantly

// ── load + re-id the recorded session into wire blocks ─────────────────────────
// parse() reads the JSONL correctly but emits engine ids ("<eid>:u", "<eid>:r",
// "<eid>:<part>"). The wire fold guard (isDurableId) only accepts the prefix form
// (u:/a:/r:/s:). So prefix by kind — keeping the original id as the unique tail.
function kindPrefix(kind) {
	if (kind === "user") return "u";
	if (kind === "tool_result") return "r";
	return "a"; // thinking / text / tool_call all live on the assistant message
}

function loadBaseBlocks() {
	const raw = fs.readFileSync(SAMPLE, "utf8");
	const { meta, blocks } = parse(raw);
	const turnSpan = blocks.reduce((m, b) => Math.max(m, b.turn), 0) + 1;
	return { meta, blocks, turnSpan, orderSpan: blocks.length };
}

// Project an engine block → a fresh WireBlock for loop N. Ids and callIds are made
// unique per loop while preserving the durable prefix and the call/result pairing
// (both halves of a pair get the same #L<loop> callId suffix). turn/order offset by
// the loop so growth stays monotonic.
function toWire(b, loop, turnSpan, orderSpan) {
	return {
		id: `${kindPrefix(b.kind)}:L${loop}:${b.id}`,
		kind: b.kind,
		turn: b.turn + loop * turnSpan,
		order: b.order + loop * orderSpan,
		text: b.text,
		tokens: b.tokens,
		...(b.toolName != null ? { toolName: b.toolName } : {}),
		...(b.callId != null ? { callId: `${b.callId}#L${loop}` } : {}),
		...(b.model != null ? { model: b.model } : {}),
		...(b.isError ? { isError: true } : {}),
	};
}

// ── selftest: validate the pipeline without opening a socket ───────────────────
if (process.argv.includes("--selftest")) {
	const { meta, blocks, turnSpan, orderSpan } = loadBaseBlocks();
	const hist = {};
	for (const b of blocks) hist[b.kind] = (hist[b.kind] || 0) + 1;
	const wire = blocks.map((b) => toWire(b, 0, turnSpan, orderSpan));
	const foldable = wire.filter((w) => w.kind === "thinking" || w.kind === "text" || w.kind === "tool_result");
	const allFoldableDurable = foldable.every((w) => isDurableId(w.id));
	const totalTokens = wire.reduce((s, w) => s + w.tokens, 0);
	// pairing check: every tool_result callId has a matching tool_call callId
	const callIds = new Set(wire.filter((w) => w.kind === "tool_call").map((w) => w.callId));
	const orphanResults = wire.filter((w) => w.kind === "tool_result" && w.callId && !callIds.has(w.callId)).length;
	console.log("title:", meta.title, "| model:", meta.model);
	console.log("blocks:", blocks.length, "| kinds:", JSON.stringify(hist));
	console.log("turnSpan:", turnSpan, "| total tokens:", totalTokens);
	console.log("first ids:", wire.slice(0, 5).map((w) => w.id));
	console.log("all foldable ids durable:", allFoldableDurable);
	console.log("orphan tool_results (want 0):", orphanResults);
	if (!allFoldableDurable || orphanResults > 0) {
		console.error("SELFTEST FAILED");
		process.exit(1);
	}
	console.log("SELFTEST OK");
	process.exit(0);
}

// ── the server ─────────────────────────────────────────────────────────────────
const { meta, blocks, turnSpan, orderSpan } = loadBaseBlocks();
const wss = new WebSocketServer({ host: "127.0.0.1", port: PORT });
let reqId = 0;

// Enter-to-step support (STEP=1): one shared readline, resolved per keypress.
let stepWaiter = null;
if (STEP) {
	const rl = readline.createInterface({ input: process.stdin });
	rl.on("line", () => {
		if (stepWaiter) {
			const w = stepWaiter;
			stepWaiter = null;
			w();
		}
	});
}
const waitStep = () => new Promise((r) => (stepWaiter = r));

wss.on("connection", (ws) => {
	console.log("GUI connected");
	let alive = true;
	ws.on("close", () => {
		alive = false;
		console.log("GUI disconnected");
	});
	ws.on("message", (d) => {
		let m;
		try {
			m = JSON.parse(d.toString());
		} catch {
			return;
		}
		if (m.type === "completeRequest") {
			// A conductor asked to borrow the model. Real pi would run it; we hand back junk.
			send(ws, {
				type: "completeResult",
				reqId: m.reqId,
				ok: true,
				text: JUNK,
				model: "fake-model",
				inputTokens: est(m.system) + est(m.prompt),
				outputTokens: est(JUNK),
			});
			console.log(`completeRequest #${m.reqId} → junk (${est(m.prompt)} tok prompt)`);
		} else if (m.type === "plan") {
			const n = (m.ops?.length || 0) + (m.groups?.length || 0);
			if (n) console.log(`plan #${m.reqId}: ${m.ops?.length || 0} fold ops, ${m.groups?.length || 0} groups (ignored)`);
		}
		// unfoldResult / recallResult: the app answering an agent tool the fake never called — ignore.
	});

	send(ws, {
		type: "hello",
		protocolVersion: PROTOCOL_VERSION,
		sessionId: "mock-" + process.pid,
		meta: { title: meta.title || "fake pi session", cwd: meta.cwd || "", model: meta.model || "fake-model", contextWindow: CW, format: "pi" },
	});

	void run(ws, () => alive);
});

function send(ws, obj) {
	try {
		ws.send(JSON.stringify(obj));
	} catch {
		/* socket gone */
	}
}

function syncOne(ws, block, full = false) {
	send(ws, { type: "sync", reqId: ++reqId, full, blocks: [block], contextWindow: CW });
}

async function run(ws, alive) {
	let loop = 0;
	let firstOfStream = true;
	while (alive()) {
		for (let i = 0; i < blocks.length && alive(); i++) {
			const wire = toWire(blocks[i], loop, turnSpan, orderSpan);

			// GROW=0 resets the store at the top of each loop with a full sync.
			const full = !GROW && i === 0;
			if (firstOfStream) firstOfStream = false;

			if (STEP) {
				console.log(`[step] turn ${wire.turn} ${wire.kind} (${wire.tokens} tok) — press Enter`);
				await waitStep();
				if (!alive()) return;
				syncOne(ws, wire, full);
				continue;
			}

			if (GENERATED.has(wire.kind)) {
				// "type" the block at TPS, showing the ghost while it generates.
				send(ws, { type: "stream", phase: "start", kind: wire.kind, contentIndex: i });
				await sleep((wire.tokens / TPS) * 1000);
				if (!alive()) return;
				syncOne(ws, wire, full);
				send(ws, { type: "stream", phase: "abort", kind: wire.kind, contentIndex: -1 }); // sweep ghost
			} else {
				// tool_result / user: instant. Tiny yield so the app can render between commits.
				syncOne(ws, wire, full);
				await sleep(10);
			}
		}
		loop++;
		console.log(GROW ? `↻ loop ${loop} — context now growing past ${loop * orderSpan} blocks` : `↻ loop ${loop} — store reset`);
	}
}

console.log(
	`mock pi listening on ws://127.0.0.1:${PORT}\n` +
		`  session: "${meta.title}" — ${blocks.length} blocks\n` +
		`  TPS=${TPS}  CW=${CW}  GROW=${GROW ? 1 : 0}  STEP=${STEP ? 1 : 0}\n` +
		`  connect: app manual port box → ${PORT}`,
);
