import test from "node:test";
import assert from "node:assert";
import fs from "node:fs/promises";
import path from "node:path";

test("E2E Demo Transcript Constraints", async (t) => {
    let transcriptFile;
    try {
        transcriptFile = await fs.readFile(path.join(process.cwd(), "demo-transcript.jsonl"), "utf-8");
    } catch (e) {
        assert.fail("demo-transcript.jsonl not found or unreadable. It must be generated by the implementation track.");
    }

    const lines = transcriptFile.trim().split("\n").filter(l => l.trim().length > 0);
    assert.ok(lines.length > 0, "Transcript should not be empty");

    let hasFold = false;
    let hasUnfold = false;
    let hasDigest = false;
    let configDecisionOccurred = false;
    let earlyConfigDecision = false;
    
    // Check valid JSONL and extract constraints
    for (let index = 0; index < lines.length; index++) {
        const line = lines[index];
        try {
            const event = JSON.parse(line);
            const str = JSON.stringify(event);
            
            if (str.includes('"fold"')) hasFold = true;
            if (str.includes('"unfold"')) hasUnfold = true;
            if (str.includes('"digest"')) hasDigest = true;
            
            if (!configDecisionOccurred && (str.includes("config") || str.includes("decision"))) {
                configDecisionOccurred = true;
                // If depth is explicitly in the event
                if (event.depth !== undefined) {
                    if (event.depth <= 0.15) earlyConfigDecision = true;
                } else if (event.metadata?.depth !== undefined) {
                    if (event.metadata.depth <= 0.15) earlyConfigDecision = true;
                } else {
                    // Approximate depth based on line index if not explicit
                    const depth = index / lines.length;
                    if (depth <= 0.15) earlyConfigDecision = true;
                }
            }
        } catch (e) {
            assert.fail(`Invalid JSON at line ${index + 1}: ${line}`);
        }
    }

    assert.ok(hasFold, "Transcript must contain at least one fold event");
    assert.ok(hasUnfold, "Transcript must contain at least one unfold event");
    assert.ok(hasDigest, "Transcript must contain a digest");
    assert.ok(earlyConfigDecision, "The config decision must occur early (depth <= 0.15)");
});

test("E2E Benchmark Constraints", async (t) => {
    let benchmarkFile;
    try {
        benchmarkFile = await fs.readFile(path.join(process.cwd(), "benchmark-report.json"), "utf-8");
    } catch (e) {
        assert.fail("benchmark-report.json not found or unreadable. It must be generated by the implementation track.");
    }

    let report;
    try {
        report = JSON.parse(benchmarkFile);
    } catch (e) {
        assert.fail("benchmark-report.json is not valid JSON");
    }

    // Checking token budgets are equal
    assert.ok(report.tokenBudgets, "benchmark-report.json must contain tokenBudgets");
    const budgets = Object.values(report.tokenBudgets) as number[];
    assert.ok(budgets.length >= 2, "Must have at least two token budgets to compare");
    const firstBudget = budgets[0];
    for (const b of budgets) {
        assert.strictEqual(b, firstBudget, "Token budgets must be equal across all models/baselines");
    }

    // Checking Accordion's retrievability > Baselines
    assert.ok(report.retrievability, "benchmark-report.json must contain retrievability");
    const accordionScore = report.retrievability["accordion"];
    assert.ok(accordionScore !== undefined, "Retrievability must include an 'accordion' score");

    const baselines = ["recency-truncation", "summarize-then-drop"];
    for (const baseline of baselines) {
        const score = report.retrievability[baseline];
        assert.ok(score !== undefined && score > 0, `Retrievability must include a valid '${baseline}' score > 0`);
        assert.ok(
            accordionScore > score,
            `Accordion retrievability (${accordionScore}) must be greater than ${baseline} (${score})`
        );
    }
});
