/**
 * generate-evidence.ts — Claim 1, made tangible.
 *
 * Reproduces one concrete head-to-head: the same session, the same token
 * budget, the same probe — assembled by a /compact-style summarize-then-drop
 * baseline vs. by Accordion. Writes EVIDENCE.md with the real assembled-context
 * excerpts, plus the full benchmark grid headline, plus the proof map for all
 * three claims. Exits non-zero if the story stops being true, so
 * `npm run evidence` doubles as a gate.
 *
 * Deterministic: no network, no LLM, no embeddings (keyword relevance path).
 */

import fs from "node:fs";
import { buildScenarios, compactContext } from "./compare-compact.ts";
import {
	applyDecisionsToState,
	createAccordionState,
	parseMessages,
	runConductor,
	type AccordionState,
	type AgentMessage,
} from "./conductor.ts";

const BUDGET = 1_500;
/** Preference order: verbatim-artifact scenarios make the sharpest story. */
const PREFERRED = ["exact-command", "file-and-error", "crowded-endpoint-list"];

function textOf(messages: AgentMessage[]): string {
	return messages
		.map((m: any) =>
			typeof m.content === "string" ? m.content : (m.content ?? []).map((p: any) => p.text ?? "").join("\n"),
		)
		.join("\n");
}

/** Accordion's multi-turn path, mirroring the benchmark harness: the Conductor
 *  runs after every message as the session grows, then answers the probe. */
function accordionContext(messages: AgentMessage[], probe: string, budget: number): { out: AgentMessage[]; state: AccordionState } {
	const state = createAccordionState();
	for (let end = 1; end <= messages.length; end++) {
		const prefix = messages.slice(0, end);
		const last: any = prefix.at(-1);
		const prompt = last?.role === "user" ? textOf([last]) : "continue";
		const output = runConductor({
			messages: prefix,
			incomingPrompt: prompt,
			lastCompletedTurn: null,
			budgetTokens: budget,
			state,
			workingTailTokens: 0,
		});
		applyDecisionsToState(state, output.decisions);
	}
	const final = runConductor({
		messages,
		incomingPrompt: probe,
		lastCompletedTurn: null,
		budgetTokens: budget,
		state,
		workingTailTokens: 0,
	});
	return { out: final.messages, state };
}

function excerptAround(text: string, key: string, radius = 220): string {
	const at = text.indexOf(key);
	if (at < 0) return "";
	const start = Math.max(0, at - radius);
	const end = Math.min(text.length, at + key.length + radius);
	return `${start > 0 ? "\u2026" : ""}${text.slice(start, end).trim()}${end < text.length ? "\u2026" : ""}`;
}

function compactExcerpt(text: string, scenario: { key: string }): string {
	// Show what the compact summary says where the artifact should have been:
	// the few summary lines nearest in topic, demonstrating the lossy paraphrase.
	const lines = text.split("\n").slice(0, 14);
	return lines.join("\n");
}

function main() {
	const scenarios = buildScenarios();
	const byName = new Map(scenarios.map((s) => [s.name, s]));
	const order = [...PREFERRED.filter((n) => byName.has(n)), ...scenarios.map((s) => s.name)];

	let chosen: { name: string; probe: string; key: string; compactText: string; accordionText: string } | null = null;
	const gridRows: string[] = [];

	for (const name of order) {
		const scenario = byName.get(name)!;
		const compactText = textOf(compactContext(scenario.messages, BUDGET));
		const { out } = accordionContext(scenario.messages, scenario.probe, BUDGET);
		const accordionText = textOf(out);
		const c = compactText.includes(scenario.key);
		const a = accordionText.includes(scenario.key);
		if (PREFERRED.includes(name)) {
			gridRows.push(`| ${name} | ${c ? "\u2705 kept" : "\u274c lost"} | ${a ? "\u2705 kept" : "\u274c lost"} |`);
		}
		if (!chosen && !c && a) {
			chosen = { name, probe: scenario.probe, key: scenario.key, compactText, accordionText };
		}
	}

	if (!chosen) {
		console.error("EVIDENCE GATE FAILED: no scenario where compact loses the artifact and Accordion keeps it.");
		process.exit(1);
	}

	const grid = fs.existsSync("compact-comparison.json")
		? JSON.parse(fs.readFileSync("compact-comparison.json", "utf8")).proofSummary
		: null;

	const md = `# EVIDENCE — the three claims, executable

*Generated by \`npm run evidence\` on ${new Date().toISOString().slice(0, 10)}. Deterministic: no network, no LLM judge — every number below regenerates from this repo.*

**Tagline:** agent memory should be **bidirectional**. The agent should be able to reach back into its own history, not just receive whatever the system decides to show it.

---

## Claim 1 — Non-destructive folding preserves what compaction destroys

**The number** (full deterministic grid, \`npm run compare:compact\`):
${grid ? `
> **${grid.cells} cells · Accordion score ${grid.accordionScore * 100}% vs /compact-style ${grid.compactScore * 100}% · ${grid.accordionWinsVsCompact} wins / ${grid.compactWinsVsAccordion} losses · ${grid.accordionBudgetViolations} budget violations · +${grid.accordionAdvantagePoints}pp advantage.**
` : "> run `npm run compare:compact` to regenerate the grid summary."}

**The one compelling example** — scenario \`${chosen.name}\`, identical ${BUDGET.toLocaleString()}-token budget, probe: \u201c${chosen.probe}\u201d

The verbatim artifact the answer depends on:

\`\`\`
${chosen.key}
\`\`\`

What the **/compact-style summary** sends the model (artifact paraphrased away — \u274c not present anywhere in its context):

\`\`\`
${compactExcerpt(chosen.compactText, chosen)}
\`\`\`

What **Accordion** sends the model at the same budget (\u2705 present, verbatim — the relevant turn was kept/restored as a view over preserved history):

\`\`\`
${excerptAround(chosen.accordionText, chosen.key)}
\`\`\`

Compaction can't get the artifact back — the history it summarized is gone. Accordion can, because folding never deletes: the digest is a *view*, addressed \u27e6t\u2026\u27e7, recoverable by the Conductor, the human, or the agent itself.

Spot-checks across the verbatim-artifact scenarios at this budget:

| scenario | /compact-style | Accordion |
| --- | --- | --- |
${gridRows.join("\n")}

## Claim 2 — The agent can actively recover context it needs

Executable, not aspirational — \`src/agent-tools.test.ts\` (run with \`npm test\`):

- **recall purity** — the agent reads a folded turn in FULL; live context byte-identical before/after.
- **unfold under pressure** — an *agent-issued* unfold restores the needle on the next assembly; the grace period keeps it open even under budget pressure; budget invariant holds.
- **learning** — the agent reaching back is a correction event: the calibrated fold target measurably rises on the next turn. The Conductor learns from the agent.
- **guardrails** — the agent can fold turns it's done with; pins are respected; the current working turn is refused.
- **addressability** — every fold level carries its \u27e6t\u2026\u27e7 turn address, so the digest itself tells the agent where to reach.

Live (pi build with extension tools): the extension registers \`accordion_recall\`, \`accordion_unfold\`, \`accordion_fold\` — ask the agent for something only a folded turn contains and watch it reach back. The app's **replay** ends on this exact beat.

## Claim 3 — The Conductor maintains performance autonomously

- \`benchmark-report.json\` (\`npm run\` demo generator): a long session crossing budget repeatedly with **zero human context interventions** — retrievability 1.0 for Accordion vs degraded recency/compact baselines.
- 56/56 deterministic tests, including: budget invariant, protected tail, tool-pair atomicity, proactive relative-outlier rescue, graduated minimal-depth folding, and the self-calibrating target (asymmetric, idempotent, clamped, pinnable).
- \`npm run proof:refresh\` regenerates the LLM-judged proof gates on a machine with Ollama.

---

*Reproduce: \`npm run evidence\` (this file) · \`npm test\` · \`npm run compare:compact\` · \`node --experimental-strip-types src/generate-demo-transcript.ts\`.*
`;

	fs.writeFileSync("EVIDENCE.md", md);
	console.log(`EVIDENCE.md written — scenario "${chosen.name}": compact \u274c, accordion \u2705 at budget ${BUDGET}.`);
}

main();
